import Nav from "./components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, onChange }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
