import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, onChange }) {
  return (
    <html lang="en">
      <body>
        <Header onChange={onChange} />
        <div style={{ marginTop: "10%" }}>{children}</div>
      </body>
    </html>
  );
}
